// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viaitelunzniuylcwpos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYWl0ZWx1bnpuaXV5bGN3cG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjgzNDAsImV4cCI6MjA2MTUwNDM0MH0.rF7ufqpV6oKtM8Z5SBvNTah1yImVeX7EvE7k5-T1YxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);